export const ADD_POSITION = 'ADD_POSITION';
export const REMOVE_POSITION = 'REMOVE_POSITION';
export const SET_FORM_VALUES = 'SET_FORM_VALUES';
export const SHOW_BTN_CANCEL = 'SHOW_BTN_CANCEL';
export const HIDE_BTN_CANCEL = 'HIDE_BTN_CANCEL';
export const FILTER_LIST = 'FILTER_LIST';

export default {
  ADD_POSITION,
  REMOVE_POSITION,
  SET_FORM_VALUES,
  SHOW_BTN_CANCEL,
  HIDE_BTN_CANCEL,
  FILTER_LIST,
};